/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.SQLException;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import dao.ClienteDAO;
import dao.Conexao;
import dao.ProdutoDAO;
import model.Cliente;

/**
 *
 * @author frerp
 */
public class TelaPerfilCliente extends javax.swing.JFrame {
    private Cliente cliente;


    /**
     * Creates new form TelaPerfilCliente
     */
    public TelaPerfilCliente(Cliente cliente) {
        initComponents();
        this.cliente = cliente;
        nomeCliente.setText(cliente.getNome());
        emailCliente.setText(cliente.getEmail());
        senhaCliente.setText(cliente.getSenha());
        endeCliente.setText(cliente.getEndereco());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        pnlFundo = new javax.swing.JPanel();
        pnlAbaLateral = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();
        telaListadeDesejos = new javax.swing.JButton();
        telaCarrinhoDeCompras = new javax.swing.JButton();
        historicoPedidos = new javax.swing.JButton();
        sairConta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nomeCliente = new javax.swing.JTextField();
        emailCliente = new javax.swing.JTextField();
        senhaCliente = new javax.swing.JTextField();
        endeCliente = new javax.swing.JTextField();
        editarNome = new javax.swing.JButton();
        editarEmail = new javax.swing.JButton();
        editEndereco = new javax.swing.JButton();
        editarSenha = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        voltarTelaPrincipal = new javax.swing.JButton();

        jButton7.setText("jButton7");

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);

        pnlFundo.setBackground(new java.awt.Color(204, 204, 255));

        pnlAbaLateral.setBackground(new java.awt.Color(0, 35, 100));

        lblFoto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFoto.setForeground(new java.awt.Color(204, 204, 255));
        lblFoto.setText("Foto Perfil");

        telaListadeDesejos.setBackground(new java.awt.Color(153, 153, 255));
        telaListadeDesejos.setForeground(new java.awt.Color(0, 35, 100));
        telaListadeDesejos.setText("Lista de desejos");
        telaListadeDesejos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    telaListadeDesejosActionPerformed(evt);
                } catch (SQLException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });

        telaCarrinhoDeCompras.setBackground(new java.awt.Color(153, 153, 255));
        telaCarrinhoDeCompras.setForeground(new java.awt.Color(0, 35, 100));
        telaCarrinhoDeCompras.setText("Carrinho de compras");
        telaCarrinhoDeCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telaCarrinhoDeComprasActionPerformed(evt);
            }
        });

        historicoPedidos.setBackground(new java.awt.Color(153, 153, 255));
        historicoPedidos.setForeground(new java.awt.Color(0, 35, 100));
        historicoPedidos.setText("Histórico de pedidos");
        historicoPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historicoPedidosActionPerformed(evt);
            }
        });

        sairConta.setText("Sair");
        sairConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairContaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAbaLateralLayout = new javax.swing.GroupLayout(pnlAbaLateral);
        pnlAbaLateral.setLayout(pnlAbaLateralLayout);
        pnlAbaLateralLayout.setHorizontalGroup(
            pnlAbaLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAbaLateralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFoto)
                .addGap(96, 96, 96))
            .addGroup(pnlAbaLateralLayout.createSequentialGroup()
                .addGroup(pnlAbaLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAbaLateralLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(pnlAbaLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(telaCarrinhoDeCompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(telaListadeDesejos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(historicoPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlAbaLateralLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(sairConta)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        pnlAbaLateralLayout.setVerticalGroup(
            pnlAbaLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAbaLateralLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(lblFoto)
                .addGap(50, 50, 50)
                .addComponent(telaCarrinhoDeCompras)
                .addGap(18, 18, 18)
                .addComponent(telaListadeDesejos)
                .addGap(18, 18, 18)
                .addComponent(historicoPedidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sairConta)
                .addGap(20, 20, 20))
        );

        jLabel1.setBackground(new java.awt.Color(0, 35, 100));
        jLabel1.setForeground(new java.awt.Color(0, 35, 100));
        jLabel1.setText("Nome:");

        jLabel2.setForeground(new java.awt.Color(0, 35, 100));
        jLabel2.setText("E-mail:");

        jLabel3.setForeground(new java.awt.Color(0, 35, 100));
        jLabel3.setText("Senha:");

        jLabel4.setForeground(new java.awt.Color(0, 35, 100));
        jLabel4.setText("Endereço:");

        emailCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailClienteActionPerformed(evt);
            }
        });

        editarNome.setText("Editar");
        editarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    editarNomeActionPerformed(evt);
                } catch (SQLException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });

        editarEmail.setText("Editar");
        editarEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    editarEmailActionPerformed(evt);
                } catch (SQLException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });

        editEndereco.setText("Editar");
        editEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    editEnderecoActionPerformed(evt);
                } catch (SQLException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });

        editarSenha.setText("Editar");
        editarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    editarSenhaActionPerformed(evt);
                } catch (SQLException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 35, 100));
        jLabel5.setText("Informações de usuário");

        voltarTelaPrincipal.setText("Voltar a comprar");
        voltarTelaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    voltarTelaPrincipalActionPerformed(evt);
                } catch (SQLException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });

        javax.swing.GroupLayout pnlFundoLayout = new javax.swing.GroupLayout(pnlFundo);
        pnlFundo.setLayout(pnlFundoLayout);
        pnlFundoLayout.setHorizontalGroup(
            pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFundoLayout.createSequentialGroup()
                .addComponent(pnlAbaLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(voltarTelaPrincipal)
                        .addGap(20, 20, 20))
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlFundoLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(29, 29, 29))
                            .addGroup(pnlFundoLayout.createSequentialGroup()
                                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)))
                                .addGap(18, 18, 18)
                                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeCliente)
                                    .addComponent(emailCliente)
                                    .addComponent(senhaCliente)
                                    .addComponent(endeCliente))))
                        .addGap(12, 12, 12)
                        .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editarNome)
                            .addComponent(editarEmail)
                            .addComponent(editarSenha)
                            .addComponent(editEndereco))
                        .addGap(94, 94, 94))))
        );
        pnlFundoLayout.setVerticalGroup(
            pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAbaLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlFundoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(voltarTelaPrincipal)
                .addGap(98, 98, 98)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarNome))
                .addGap(18, 18, 18)
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(emailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarEmail))
                .addGap(18, 18, 18)
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(senhaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarSenha))
                .addGap(18, 18, 18)
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(endeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editEndereco))
                .addGap(60, 113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailClienteActionPerformed
        emailCliente.setText(cliente.getEmail());
    }//GEN-LAST:event_emailClienteActionPerformed

    private void editarNomeActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButton4ActionPerformed
        
        String nNome = nomeCliente.getText();
        Connection conexao = new Conexao().getConnection();
        ClienteDAO clienteDAO = new ClienteDAO (conexao);
        clienteDAO.updateClienteNome(cliente, nNome);
        JOptionPane.showMessageDialog(null,"Atualização feita com sucesso");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void editarEmailActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButton1ActionPerformed
        String nEmail = emailCliente.getText();
        Connection conexao = new Conexao().getConnection();
        ClienteDAO clienteDAO = new ClienteDAO (conexao);
        clienteDAO.updateClienteEmail(cliente,nEmail);
        JOptionPane.showMessageDialog(null,"Atualização feita com sucesso");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void editEnderecoActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButton3ActionPerformed
        String nEndereco = endeCliente.getText();
        Connection conexao = new Conexao().getConnection();
        ClienteDAO clienteDAO = new ClienteDAO (conexao);
        clienteDAO.updateClienteEndereco(cliente,nEndereco);
        JOptionPane.showMessageDialog(null,"Atualização feita com sucesso");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void voltarTelaPrincipalActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_voltarTelaPrincipalActionPerformed
        TelaPrincipal_4 telaPrincipal = new TelaPrincipal_4(cliente);
        telaPrincipal.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_voltarTelaPrincipalActionPerformed

    private void editarSenhaActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButton9ActionPerformed
        String nSenha = senhaCliente.getText();
        Connection conexao = new Conexao().getConnection();
        ClienteDAO clienteDAO = new ClienteDAO (conexao);
        clienteDAO.updateClienteSenha(cliente,nSenha);
        JOptionPane.showMessageDialog(null,"Atualização feita com sucesso");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void telaListadeDesejosActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButton6ActionPerformed
        
        TelaCarrinhoDeCompras telaCarrinhoDeCompras = new TelaCarrinhoDeCompras(cliente);
        telaCarrinhoDeCompras.setExtendedState(JFrame.MAXIMIZED_BOTH);
        telaCarrinhoDeCompras.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void telaCarrinhoDeComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        TelaListaDeDesejos telaListaDeDesejos = new TelaListaDeDesejos();
        telaListaDeDesejos.setExtendedState(JFrame.MAXIMIZED_BOTH);
        telaListaDeDesejos.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void historicoPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void sairContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairContaActionPerformed
        this.dispose();
        TelaEntrada voltaSistema = new TelaEntrada();
        voltaSistema.setVisible(true);
        
    }//GEN-LAST:event_sairContaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPerfilCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPerfilCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPerfilCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPerfilCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPerfilCliente(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editEndereco;
    private javax.swing.JButton editarEmail;
    private javax.swing.JButton editarNome;
    private javax.swing.JButton editarSenha;
    private javax.swing.JTextField emailCliente;
    private javax.swing.JTextField endeCliente;
    private javax.swing.JButton historicoPedidos;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JTextField nomeCliente;
    private javax.swing.JPanel pnlAbaLateral;
    private javax.swing.JPanel pnlFundo;
    private javax.swing.JButton sairConta;
    private javax.swing.JTextField senhaCliente;
    private javax.swing.JButton telaCarrinhoDeCompras;
    private javax.swing.JButton telaListadeDesejos;
    private javax.swing.JButton voltarTelaPrincipal;
    // End of variables declaration//GEN-END:variables
}
